---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggsankey)
library(gtsummary)

#filter to 28 days within their device implant
# for candidates that have multiple devices they will have total follow up longer than 28 days

reduced_data = iabps_impellas %>% filter(iabp_time <= 28 | impella_time <= 28)
reduced_data %>% group_by(PX_ID)
# filter out patients who had iabp implant before policy change
# these patients got an impella after 10/18 which is why they were still in the df
reduced_data = reduced_data %>% group_by(PX_ID) %>% filter(first(unique_date) >= "2018-10-18")

# filter out post removal observations (don't want post delisting deaths)
reduced_data = reduced_data %>% mutate(
  removal = ifelse(grepl("CAN_REM_DT", unique_event), 1, 0)) %>% 
  mutate(post_removal = cumsum(removal)) %>% 
  filter(!(post_removal == 1 & !grepl("CAN_REM_DT", unique_event))) %>%
  mutate(combined = case_when(
    any(post_iabp == 1 & post_impella == 1) ~ 1,
    TRUE ~ 0)) 

combined_support = reduced_data %>% filter(any(post_iabp == 1 & post_impella == 1)) %>% filter(unique_event != "iabp_date") %>% ungroup()

reduced_data = reduced_data %>% filter(combined == 0) %>% ungroup()
reduced_data = rbind(combined_support, reduced_data) %>% group_by(PX_ID)

# establish levels for sankey
sankey_data = reduced_data %>% mutate(
  post_iabp = ifelse(is.na(post_iabp), 0, post_iabp),
  post_impella = ifelse(is.na(post_impella), 0, post_impella)
  ) %>% mutate(
  Mechanical_Circulatory_Support = case_when(
    post_iabp == 1 & post_impella == 0 ~ "IABP",
    TRUE ~ "Percutaneous VAD")) 
# %>% mutate(
#  second_decision = case_when(
#    first_decision == "Impella" ~ "Impella",
#    any(post_impella == 1) ~ "Impella",
#    TRUE ~ "IABP only"
#  )
  
  #ifelse(any(post_iabp == 1), "IABP", "Percutaneous VAD"))
mutate(
  Outcome = case_when(
    any(grepl("durable_lvad_date", unique_event)) ~ "Dischargeable LVAD",
    any(grepl("REC_TX_DT", unique_event)) ~ "Transplanted",
    any(grepl("death_date", unique_event)) & !any(grepl("REC_TX_DT", unique_event)) ~ "Died",
    !any(grepl("REC_TX_DT", unique_event)) & !any(grepl("DEATH_DT", unique_event)) & any(grepl("CAN_REM_DT", unique_event)) ~ "Delisted",
    Mechanical_Circulatory_Support == "IABP" ~ "Extended IABP Support",
    TRUE ~ "Extended Percutaneous VAD Support"
  )
)

```


```{r sankey}
# set up sankey df
data_for_sankey <- sankey_data %>% 
  slice(1) %>% 
  ungroup() %>%
  select(Mechanical_Circulatory_Support, Outcome) %>%
  make_long(Mechanical_Circulatory_Support, Outcome)
data_for_sankey

ctr_plot <- data_for_sankey %>%
  dplyr::group_by(node)%>%
  tally()

data_for_sankey <- merge(data_for_sankey,
             ctr_plot, 
             by.x = 'node', 
             by.y = 'node', 
             all.x = TRUE)

sankey_plot <- ggplot(data_for_sankey, aes(x = x,                        
                     next_x = next_x,                                     
                     node = node,
                     next_node = next_node,        
                     fill = factor(node),
                     label = paste0(node, " = ", n))) +
  geom_sankey(flow.alpha = 0.5,
                      node.color = "black",
                      show.legend = TRUE)+ 
  geom_sankey_label(color = "black", fill = "white") +
  theme_bw() + 
  theme(legend.position = 'none', 
        axis.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_text(size = 10)) + 
  labs(fill = 'Nodes', title = 'Outcomes within 28 Days after IABP and pVAD Implantation')

sankey_plot

```



```{r statuses}

newlist <- reduced_data %>% select(c("PX_ID", "unique_date", "unique_event")) %>%
  pivot_wider(names_from = unique_event, values_from = unique_date) %>%
  rename("both_mcs" = "iabp_date, impella_date") %>%
  rename("transplant_dt" = "REC_TX_DT, CAN_REM_DT") %>%
  rename("death_dt" = "CAN_REM_DT, death_date") %>%
  rename("impella_transplant_dt" = "REC_TX_DT, CAN_REM_DT, impella_date") %>%
  rename("transplant_death_dt" = "REC_TX_DT, CAN_REM_DT, death_date") %>%
  mutate(mcs_date = pmax(iabp_date, impella_date, both_mcs, impella_transplant_dt, na.rm = TRUE)) %>%
  mutate(mcs_date = case_when(
    !is.na(impella_transplant_dt) ~ impella_transplant_dt,
    TRUE ~ mcs_date)) %>%
  mutate(mcs_type = case_when(
    !is.na(iabp_date) ~ "IABP",
    TRUE ~ "pVAD")) %>%
  mutate(transplant_dt = case_when(
    !is.na(impella_transplant_dt) ~ impella_transplant_dt,
    TRUE ~ transplant_dt)) %>%
  mutate(outcome_date = case_when(
    mcs_date <= durable_lvad_date ~ pmin(transplant_dt, death_dt, CAN_REM_DT, transplant_death_dt, durable_lvad_date, na.rm = TRUE),
    TRUE ~ pmin(transplant_dt, death_dt, CAN_REM_DT, transplant_death_dt, na.rm = TRUE))) %>%
  mutate(outcome = case_when(
    !is.na(durable_lvad_date) ~ "LVAD",
    !is.na(transplant_dt) | !is.na(transplant_death_dt) ~ "Transplanted",
    !is.na(death_dt) ~ "Died",
    is.na(CAN_REM_DT) ~ "On Waitlist",
    TRUE ~ "Delisted")) %>%
  select(PX_ID, mcs_date, outcome_date, mcs_type, outcome) %>%
  mutate(extended_support = case_when(
    is.na(outcome_date) ~ 1,
    TRUE ~ 0)) %>%
  mutate(outcome_date = case_when(
    is.na(outcome_date) ~ as.Date(mcs_date) + 28,
    TRUE ~ outcome_date)) %>%
  left_join(stathist_thor %>% select(PX_ID, CANHX_BEGIN_DT, CANHX_END_DT, CANHX_STAT_CD), by = "PX_ID") %>%
  group_by(PX_ID) %>% arrange(PX_ID, CANHX_BEGIN_DT) %>% 
  mutate(CANHX_END_DT = case_when(
    is.na(CANHX_END_DT) ~ ymd("2024-03-31"),
    TRUE ~ CANHX_END_DT))

newlist <- newlist %>%
  mutate(standby = case_when(
    any(mcs_date >= CANHX_BEGIN_DT & mcs_date <= CANHX_END_DT) ~ 0,
    TRUE ~ 1))

newlist1 <- newlist %>%
  filter(standby == 0) %>%
  filter(row_number() >= min(which(mcs_date >= CANHX_BEGIN_DT & mcs_date <= CANHX_END_DT))) %>%
  mutate(standby1 = case_when(
    any(outcome_date >= CANHX_BEGIN_DT & outcome_date <= CANHX_END_DT) ~ 0,
    TRUE ~ 1))

newlist1.1 <- newlist1 %>%
  filter(standby1 == 0) %>%
  filter(row_number() <= min(which(outcome_date >= CANHX_BEGIN_DT & outcome_date <= CANHX_END_DT)))

newlist1.2 <- newlist1 %>%
  filter(standby1 == 1)
  
newlist2 <- newlist %>% filter(standby == 1) %>%
  mutate(standby1 = case_when(
    any(outcome_date >= CANHX_BEGIN_DT & outcome_date <= CANHX_END_DT) ~ 0,
    TRUE ~ 1))

newlist2.1 <- newlist2 %>%
  filter(standby1 == 0) %>%
  filter(row_number() <= min(which(outcome_date >= CANHX_BEGIN_DT & outcome_date <= CANHX_END_DT)))

newlist2.2 <- newlist2 %>%
  filter(standby1 == 1)

newlist <- rbind(newlist1.1, newlist1.2, newlist2.1, newlist2.2) %>% group_by(PX_ID) %>%
  mutate(CANHX_STAT_CD_REV = case_when(
    CANHX_STAT_CD == 2999 ~ lag(CANHX_STAT_CD),
    TRUE ~ CANHX_STAT_CD)) %>%
  mutate(CANHX_STAT_CD_REV = case_when(
    is.na(CANHX_STAT_CD_REV) ~ 2999,
    TRUE ~ CANHX_STAT_CD_REV)) %>%
  mutate(Last_Status = case_when(
    CANHX_STAT_CD_REV == 1110 | CANHX_STAT_CD_REV == 2110 ~ 1,
    CANHX_STAT_CD_REV == 1120 | CANHX_STAT_CD_REV == 2120 ~ 2,
    CANHX_STAT_CD_REV == 2130 ~ 3,
    CANHX_STAT_CD_REV == 2140 ~ 4,
    CANHX_STAT_CD_REV == 2150 ~ 5,
    CANHX_STAT_CD_REV == 2160 ~ 6,
    TRUE ~ 999))

new_list <- newlist %>% slice(n()) %>% left_join(cand_list1 %>% select(PX_ID, dlvad_eligible, VadBrandId, OtherSpecify), by = "PX_ID") %>%
  select(-c("standby", "standby1", "CANHX_STAT_CD", "CANHX_STAT_CD_REV")) %>%
  left_join(cand_thor %>% select(PX_ID, CAN_LISTING_DT, CAN_INIT_ACT_STAT_CD, CAN_RACE, CAN_ETHNICITY_SRTR, CAN_GENDER, CAN_ABO, CAN_DGN, CAN_AGE_AT_LISTING, CAN_BMI, CAN_PRIMARY_PAY, CAN_FUNCTN_STAT, CAN_PCW_MEAN, CAN_HGT_CM, CAN_WGT_KG, CAN_CARDIAC_OUTPUT, CAN_LISTING_CTR_CD), by = "PX_ID")

new_list <- new_list %>%
  mutate(time_from_listing_to_mcs = as.numeric(difftime(mcs_date, CAN_LISTING_DT, units = "days")),
         first_status = case_when(
           CAN_INIT_ACT_STAT_CD == 1110 | CAN_INIT_ACT_STAT_CD == 2110 ~ 1,
           CAN_INIT_ACT_STAT_CD == 1120 | CAN_INIT_ACT_STAT_CD == 2120 ~ 2,
           CAN_INIT_ACT_STAT_CD == 2130 ~ 3,
           CAN_INIT_ACT_STAT_CD == 2140 ~ 4,
           CAN_INIT_ACT_STAT_CD == 2150 ~ 5,
           CAN_INIT_ACT_STAT_CD == 2160 ~ 6,
           TRUE ~ 999),
         sex = ifelse(CAN_GENDER == "M", "Male", "Female"),
         sex = factor(sex, levels = c("Male", "Female")),
         bmi = case_when(
           CAN_BMI < 18 ~ "Underweight",
           CAN_BMI >= 18 & CAN_BMI < 25 ~ "Normal",
           CAN_BMI >= 25 & CAN_BMI < 30 ~ "Overweight",
           CAN_BMI >= 30 ~ "Obese",
           TRUE ~ "Unknown"),
         bmi = factor(bmi, levels = c("Normal", "Underweight", "Overweight", "Obese", "Unknown")),
         race = case_when(
           is.na(CAN_RACE) & CAN_ETHNICITY_SRTR == "LATINO" ~ "Hispanic/Latino",
           CAN_RACE == 8 & CAN_ETHNICITY_SRTR == "NLATIN" ~ "White",
           CAN_RACE == 16 & CAN_ETHNICITY_SRTR == "NLATIN" ~ "Black",
           CAN_RACE == 64 & CAN_ETHNICITY_SRTR == "NLATIN" ~ "Asian",
           TRUE ~ "Other"),
         race = factor(race, levels = c("White", "Black", "Hispanic/Latino", "Asian", "Other")),
         age_at_listing = CAN_AGE_AT_LISTING,
         age_at_mcs = floor(CAN_AGE_AT_LISTING + time_from_listing_to_mcs / 365.25),
         functional = case_when(
           (CAN_FUNCTN_STAT == 2010 | CAN_FUNCTN_STAT == 2020 | CAN_FUNCTN_STAT == 2030 | CAN_FUNCTN_STAT == 2040) ~ "Low",
           (CAN_FUNCTN_STAT == 2050 | CAN_FUNCTN_STAT == 2060 | CAN_FUNCTN_STAT == 2070) ~ "Intermediate",
           (CAN_FUNCTN_STAT == 2080 | CAN_FUNCTN_STAT == 2090 | CAN_FUNCTN_STAT == 2100) ~ "High",
           TRUE ~ "Unknown"),
         functional = factor(functional, levels = c("High", "Intermediate", "Low", "Unknown")),
         payor = case_when(
           CAN_PRIMARY_PAY %in% c(2,3,4,5,6,7,13) ~ "Public",
           CAN_PRIMARY_PAY == 1 ~ "Private",
           TRUE ~ "Other"),
         blood_type = factor(
           case_when(
             CAN_ABO %in% c("A", "A1", "A2") ~ "A",
             CAN_ABO %in% c("A1B", "A2B") ~ "AB",
             TRUE ~ CAN_ABO)),
         payor = factor(payor, levels = c("Private", "Public", "Other")),
         diagnosis = case_when(
          CAN_DGN > 999 & CAN_DGN < 1007 ~ "Dilated Cardiomyopathy, Non-Ischemic",
          CAN_DGN == 1007 | CAN_DGN == 1200 ~ "Ischemic Cardiomyopathy",
          CAN_DGN > 1048 & CAN_DGN < 1100 ~ "Restrictive Cardiomyopathy",
          TRUE ~ "Other"),
         diagnosis = factor(diagnosis, levels = c("Dilated Cardiomyopathy, Non-Ischemic", "Ischemic Cardiomyopathy", 
                                                  "Restrictive Cardiomyopathy", "Other")),
         pcwp = CAN_PCW_MEAN,
         body_surface_area = 0.007184 * (CAN_HGT_CM)^(0.725) * CAN_WGT_KG^(0.425),
         cardiac_index = as.numeric(CAN_CARDIAC_OUTPUT/body_surface_area),
         cardiac_index = ifelse(cardiac_index > 10, NA, cardiac_index)) %>%
  select(-c("CAN_INIT_ACT_STAT_CD", "CAN_RACE", "CAN_ETHNICITY_SRTR", "CAN_GENDER", "CAN_DGN", "CAN_AGE_AT_LISTING", "CAN_BMI",
            "CAN_PRIMARY_PAY", "CAN_FUNCTN_STAT", "CAN_PCW_MEAN", "CAN_HGT_CM", "CAN_WGT_KG", "CAN_CARDIAC_OUTPUT"))

new_list1 <- new_list %>% left_join(risk_strat_data_hr %>% select(PX_ID, ChangeDt, CurrTherVasoactiveSupport, CurrTherDopamine, CurrTherDobutamine, CurrTherMilrinone, CurrTherEpinephrine, CurrTherNorephinephrine, CurrTherVasopressin, CurrTherPulVas), by = "PX_ID") %>% group_by(PX_ID) %>% arrange(ChangeDt)

new_list2 <- new_list1 %>%
  mutate(data_within7days_mcs = case_when(
    as.numeric(difftime(mcs_date, ChangeDt, units = "days")) <= 7 & as.numeric(difftime(mcs_date, ChangeDt, units = "days")) > 0 ~ 1,
    TRUE ~ 0)) %>% group_by(PX_ID) %>%
  mutate(standby = case_when(
    any(data_within7days_mcs == 1) ~ 1,
    TRUE ~ 0))

new_list2.1 <- new_list2 %>% filter(standby == 0) %>% slice(1)
new_list2.2 <- new_list2 %>% filter(standby == 1) %>% filter(data_within7days_mcs == 1) %>% slice(n())
new_list2 <- rbind(new_list2.1, new_list2.2) %>% select(-c("standby"))  

new_list3 <- new_list2 %>% left_join(risk_strat_data_hr %>% select(PX_ID, HemoDt, HemoObtainedOnSupport, HemoSbp, HemoDbp, HemoPcwp, HemoCardiacIndex, HemoSvo2), by = "PX_ID") %>% group_by(PX_ID) %>% arrange(HemoDt) %>%
  mutate(data_before_outcome = case_when(
    HemoDt >= as.POSIXct(mcs_date) & HemoDt <= as.POSIXct(outcome_date) ~ 1,
    TRUE ~ 0)) %>%
  mutate(standby = case_when(
    any(data_before_outcome == 1) ~ 1,
    TRUE ~ 0)) %>%
  mutate(HemoMAP = round(HemoDbp + (HemoSbp - HemoDbp) / 3))

new_list3.1 <- new_list3 %>% filter(standby == 0) %>% slice(1)
new_list3.2 <- new_list3 %>% filter(standby == 1) %>% filter(data_before_outcome == 1) %>% slice(n())
new_list3 <- rbind(new_list3.1, new_list3.2) %>% select(-c("standby")) %>%
  mutate(inotropes_before_mcs = case_when(
    data_within7days_mcs == 1 & (!is.na(CurrTherDopamine) | !is.na(CurrTherDobutamine) | !is.na(CurrTherMilrinone) | 
                                   !is.na(CurrTherEpinephrine)) ~ 1,
    TRUE ~ 0)) %>%
  mutate(extension_hemo_eligible = case_when(
    data_before_outcome == 1 & (HemoMAP < 60 | HemoPcwp > 15 | HemoSvo2 < 50 | HemoCardiacIndex < 2) ~ 1,
    TRUE ~ 0)) %>%
  mutate(hemo_measure_outcome_time = as.numeric(difftime(outcome_date, HemoDt, units = "days"))) %>%
  mutate(high_dose_inotrope = case_when(
    inotropes_before_mcs == 1 & (CurrTherDobutamine >= 7.5 | CurrTherMilrinone >= 0.5 | CurrTherEpinephrine >= 0.02) ~ 1,
    inotropes_before_mcs == 0 ~ NA,
    TRUE ~ 0)) %>%
  mutate(multi_agent_low_dose_inotropes = case_when(
    inotropes_before_mcs == 1 & high_dose_inotrope != 1 & ((CurrTherDobutamine >= 3 & CurrTherMilrinone >= 0.25) | (CurrTherDobutamine >= 3 & CurrTherEpinephrine >= 0.01) | (CurrTherDobutamine >= 3 & CurrTherDopamine >= 3) | (CurrTherMilrinone >= 0.25 & CurrTherEpinephrine >= 0.01) | (CurrTherMilrinone >= 0.25 & CurrTherDopamine >= 3) |  (CurrTherEpinephrine >= 0.01 & CurrTherDopamine >= 3)) ~ 1,
    inotropes_before_mcs == 0 ~ NA,
    TRUE ~ 0)) %>%
  mutate(LVAD = case_when(
    outcome == "LVAD" & VadBrandId == 224 ~ "HeartWare HVAD (Medtronic)",
    outcome == "LVAD" & (VadBrandId == 236 | VadBrandId == 999) ~ "HeartMate 3 LVAD (Abbott)",
    TRUE ~ NA))
```

```{r table1}
fortable1 <- newlist3 %>% ungroup()

var_label_list <- list(age_at_listing = "Age at Listing (Years)",
                       age_at_mcs = "Age at MCS Device Placement (Years)",
                       bmi = "BMI",
                       sex = "Sex",
                       race = "Race",
                       blood_type = "Blood Type",
                       functional = "Functional Status",
                       payor = "Insurance Type",
                       diagnosis = "Primary Diagnosis",
                       inotropes_before_mcs = "On Inotropes Within 7 Days Before MCS Placement",
                       high_dose_inotrope = "Single-Agent High-Dose Inotrope",
                       multi_agent_low_dose_inotropes = "2 or More Low-Dose Inotropes",
                       mcs_type = "Mechanical Circulatory Support Device")
labelled::var_label(fortable1) <- var_label_list


fortable1 %>%
  dplyr::select(
    age_at_listing, age_at_mcs, sex, race, bmi, blood_type, functional, payor, diagnosis, inotropes_before_mcs, high_dose_inotrope, 
    multi_agent_low_dose_inotropes, mcs_type) %>%
  tbl_summary(by = mcs_type, digits = list(all_categorical() ~ c(0, 1))) %>%
  add_p(test.args = all_tests("chisq.test") ~ list(workspace=2e7)) %>%
  add_overall() %>%
  remove_row_type(variables = c(age_at_mcs, high_dose_inotrope, multi_agent_low_dose_inotropes), 
                  type = "missing", level_value = ("(Missing)")) %>%
  as_gt()
```

```{r fig2}
notransplant <- fortable1 %>% filter(outcome != "Transplanted") %>%
  mutate(new_outcome = case_when(
    outcome == "On Waitlist" ~ "On Temporary MCS",
    outcome == "LVAD" ~ "Received Dischargeable LVAD",
    outcome == "Delisted" | outcome == "Died" ~ "Died/Delisted"))

number <- notransplant %>% group_by(CAN_LISTING_CTR_CD) %>%
  summarise(n = n())

notransplant <- notransplant %>% left_join(number) %>% ungroup() %>% group_by(CAN_LISTING_CTR_CD) %>% arrange(n, CAN_LISTING_CTR_CD)
  
groups = notransplant$CAN_LISTING_CTR_CD %>% unique
i = 0
notransplant$center = NA
for (g in groups) {
  i = i + 1
  notransplant[notransplant$CAN_LISTING_CTR_CD == g, ]$center = i
}


rates <- notransplant %>% ungroup() %>% group_by(CAN_LISTING_CTR_CD) %>%
  summarise(
    prop_lvad_center = sum(outcome == "LVAD") / n(),
    number_lvad = sum(outcome == "LVAD"),
    prop_lvad_whole = sum(outcome == "LVAD") / 135,
  ) %>% 
  arrange(-number_lvad) %>%
  mutate(Cum = cumsum(number_lvad))


ggplot(notransplant, aes(x = center, fill = new_outcome)) +
  geom_bar(position = "stack", stat = "count", width = 0.8) +
  theme_classic() +
  theme(legend.position = "bottom") +
  theme() +
  labs(x = "U.S. Transplant Centers", y = "Number of Candidates") +
  scale_fill_manual(name = "", values = c("#ae6320", "#b8a370", "#660000"))
```




